Added integration test for GetExchangeRate operation
OpenWiseSolutions/openhub-ri pull request #1
Opened 2017-09-08 16:10 UTC by kkovarik

Added simple end-to-end test. Test does launch entire openhub-ri application, with http client request is sent, and live target REST service (fixer.io) is replaced with mocked http server.

### CHANGES
* added dependency to openhub-web to start tests with web context & embedded servlet container (see related PR to openhub-framework which enables that)
* added simple parent AbstractIntegrationTest. does contain prepared
* added "happy scenario" test implementation for GetExchangeRate operation, see GetExchangeRateIntegrationTest

### FUTHER STEPS
* AbstractIntegrationTest could be transferred to openhub-framework with improved mock server (for example with not static port)

### SEE ALSO
* related openhub-framework PR: , this changes depend on it
* used mock server: https://github.com/mkotsur/restito

2017-09-08 17:12 UTC, pjuza requested changes
Please try to think about if parent class for integration tests don't move to OHF?

2017-09-08 17:12 UTC, pjuza commented on openhub-ext/pom.xml
> +            <groupId>org.openhubframework</groupId>
Why not for test scope only?

2017-09-08 17:12 UTC, pjuza commented on openhub-ext/src/test/java/org/openhubframework/openhub/ri/AbstractIntegrationTest.java
> +public abstract class AbstractIntegrationTest extends AbstractRITest {
I would expect that parent class for web integration tests will be in OHF in test module, like AbstractTest or AbstractDbTest. It meens also add dependency to restito ...
Another project will have to creates identical/very similar classes, why don't add it to OHF?

2017-09-10 17:59 UTC, kkovarik commented on openhub-ext/pom.xml
> +            <groupId>org.openhubframework</groupId>
Right, will change, thanks.

2017-09-11 12:37 UTC, kkovarik commented
@pjuza: Updated to correspond with new changes in openhub-framework - added tomcat dependency & custom component scan config.

2017-09-11 12:37 UTC, kkovarik commented on openhub-ext/pom.xml
> +            <groupId>org.openhubframework</groupId>
Done.

2017-09-12 10:17 UTC, closed without merging

2017-09-12 10:28 UTC, kkovarik commented
Closed, served its purpose, will be added directly to the target branch,